### ISSUE TITLE
1.0.1: version problems.

### ISSUE THREAD

**Issue by leamas** [selmf/unarr#1]
While version 1.0.1 is, well, 1.0.1 the CMakelists.txt file contains the definition 

    project(unarr VERSION 1.0.0 LANGUAGES C)

As a consequence, the pkgconfig file uses a 1.0.0 version and the library becomes *libunarr.so.1.0.0*.

Since the release is tagged, one idea could be to release a 1.0.2 fixing this?

**Comment by selmf** [comment]
1.0.1 was just a minor bugfix for the pkgconfig file so I was reluctant to increase the soversion (as there were no changes to the actual library). In hindsight this was probably a bad idea and I should have kept the versions in sync no matter how trivial the changes.

If you need the versions to match, you can patch 1.0.1 into CMakelists.txt for now. I will fix the mismatch in the next version (either 1.0.2 or 1.1.0), so there won't be any conflict.

**Comment by selmf** [comment]
Yes, the soversion should only change if there is api/abi breakage. Sorry for the confusion.

**Comment by selmf** [comment]
Fixed in https://github.com/selmf/unarr/commit/ca745b72684e156c1e1b0445f36675527264746e
