### ISSUE TITLE
QtWebApp

### ISSUE THREAD

**Issue by StefanFrings** [selmf/unarr#16]
Could you please remove the keyword "official" from your fork of my QtWebApp project?

Thank you.

**Comment by selmf** [comment]
While there is no reason not to honor your request I am a bit sad that you did not take the time to at least add one or two sentences explaining why this is necessary and where exactly the fork was declared official. Neither me nor any other person who forked QtWebApp has had any intention to make their fork appear as "official" and I had not been aware that this word was included in the repo description you gave your project at the time of the fork.
It is also not very considerate to raise this issue on an unrelated project's issue tracker. We've already exchanged mails in the past to fix some smaller bugs in QtWebApp, so you could have just reached me that way or you could have opened a pull request.

I've deleted my fork for now. Please let me know when it is safe to fork again.
