### ISSUE TITLE
1.0.1: no ctest test units

### ISSUE THREAD

**Issue by kloczek** [selmf/unarr#21]
Looks like test/ content is not integrated with cmake/ctest
```console
[tkloczko@devel-g2v x86_64-redhat-linux-gnu]$ ctest -vv
Test project /home/tkloczko/rpmbuild/BUILD/unarr-1.0.1/x86_64-redhat-linux-gnu
No tests were found!!!
```

**Comment by selmf** [comment]
In it's current state, the test/ directory is not ready for ctest integration. Right now it only consists of the unarr-test sample application, which could be used for integration testing, but would require a suitable well-defined test corpus with sample input files to fulfill this role.
I do of course have a set of files which I use locally for testing and development, but these are - for various reasons - not suitable for distribution.

I'm currently working on improving the general testing situation and adding the necessary infrastructure for unit tests, adding a test corpus for integration tests and enabling easy fuzzer testing (see #4 ).

**Comment by selmf** [comment]
Alright, with the latest push, unit tests and integration tests are set up and integrated into the CI. The amount of tests is still very modest, but that will change with time.
To build tests, you need to add:

```
-DBUILD_UNIT_TESTS=ON
-DBUILD_INTEGRATION_TESTS=ON
```
Unit tests need CMocka to work.

You can also run fuzzing tests:

```
-DBUILD_FUZZER
```

**Comment by kloczek** [comment]
I have both options enabled
```console
[tkloczko@devel-g2v SPECS]$ grep TEST rocksdb.spec
        -D WITH_ALL_TESTS=ON \
        -D WITH_TESTS=ON \
```
and ctest shows
```console
[tkloczko@pers-jacek x86_64-redhat-linux-gnu]$ ctest -vv
Test project /home/tkloczko/rpmbuild/BUILD/rocksdb-7.7.2/x86_64-redhat-linux-gnu
No tests were found!!!
```

**Comment by selmf** [comment]
Uhm no you don't. Compare your options with what I wrote. Or compare with azure-pipelines.yml.

**Comment by selmf** [comment]
Also, are you sure you are using the correct spec file?

**Comment by kloczek** [comment]
wrong ticket 😄
